spring:
 application: 
  name: praveenoruganti-spring-cloud-config-server

 cloud:
   config:
     server:
       git:
        uri: https://github.com/praveenorugantitech/praveenorugantitech-springboot/tree/master/0_Projects/praveen-spring-config-server-master
        searchPaths: config
server:
 port: 8888

